

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size: 5
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1000s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: 1000
        # 最大活跃连接数，负数为不限制
        max-active: -1
  cache:
    redis:
      time-to-live: -1 #毫秒

#以下可忽略
mybatis:
    #开启驼峰命名
  map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huanghong.demo.entity
logging:
  level:
    com.scitc.cache.mapper : debug
server:
  port: 6001